/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.List;
import java.util.ArrayList;
import metodos.*;

/**
 *
 * @author Mirko
 */
public class mainJForm extends javax.swing.JFrame {

    /**
     * Creates new form mainJForm
     */
    
    public mainJForm() {
        initComponents();
        this.cargarMetodos();
        jTextArea_texto.setLineWrap(true);
        jTextArea_resultado.setLineWrap(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton_Descifrar = new javax.swing.JButton();
        jButton_Cifrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_texto = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_clave = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_metodos = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_resultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("Metodos de cifrado Clasico");

        jButton_Descifrar.setText("Descifrar");
        jButton_Descifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DescifrarActionPerformed(evt);
            }
        });

        jButton_Cifrar.setText("Cifrar");
        jButton_Cifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CifrarActionPerformed(evt);
            }
        });

        jTextArea_texto.setColumns(20);
        jTextArea_texto.setRows(5);
        jScrollPane1.setViewportView(jTextArea_texto);

        jLabel2.setText("Introdusca un mensaje");

        jLabel3.setText("Clave:");

        jLabel4.setText("Elija un metodo de cifrado:");

        jLabel5.setText("Resultado:");

        jTextArea_resultado.setColumns(20);
        jTextArea_resultado.setRows(5);
        jScrollPane2.setViewportView(jTextArea_resultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_metodos, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton_Cifrar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton_Descifrar))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField_clave))
                        .addComponent(jScrollPane1)
                        .addComponent(jLabel4)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox_metodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Cifrar)
                    .addComponent(jButton_Descifrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CifrarActionPerformed
        String metodoSeleccionado = jComboBox_metodos.getSelectedItem().toString();
        String texto = jTextArea_texto.getText();
        int clave = Integer.valueOf(jTextField_clave.getText());
        switch(metodoSeleccionado){
            case "Transposicion por Columnas":{
                Columnas textoClaro = new Columnas();
                jTextArea_resultado.setText(textoClaro.cifrar(texto, clave));
                break;
            }
            case "Transposicion por Zig-Zag":{
                ZigZag textoClaro = new ZigZag();
                jTextArea_resultado.setText(textoClaro.cifrar(texto, clave));
                break;
            }
        }
    }//GEN-LAST:event_jButton_CifrarActionPerformed

    private void jButton_DescifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DescifrarActionPerformed
        String metodoSeleccionado = jComboBox_metodos.getSelectedItem().toString();
        String texto = jTextArea_texto.getText();
        int clave = Integer.valueOf(jTextField_clave.getText());
        switch(metodoSeleccionado){
            case "Transposicion por Columnas":{
                Columnas textoClaro = new Columnas();
                jTextArea_resultado.setText(textoClaro.descifrar(texto, clave));
                break;
            }
            case "Transposicion por Zig-Zag":{
                ZigZag textoClaro = new ZigZag();
                jTextArea_resultado.setText(textoClaro.descifrar(texto, clave));
                break;
            }
        }
    }//GEN-LAST:event_jButton_DescifrarActionPerformed
    public void cargarMetodos(){
        ArrayList<String> metodos = new ArrayList<String>();        
        metodos.add("Transposicion por Columnas");
        metodos.add("Transposicion por Zig-Zag");
        //cargar los metodos de cifrado en combobox
        for(String metodo: metodos){
            this.jComboBox_metodos.addItem(metodo);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainJForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainJForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainJForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainJForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainJForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cifrar;
    private javax.swing.JButton jButton_Descifrar;
    private javax.swing.JComboBox<String> jComboBox_metodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea_resultado;
    private javax.swing.JTextArea jTextArea_texto;
    private javax.swing.JTextField jTextField_clave;
    // End of variables declaration//GEN-END:variables
}
